{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/vkid\/autherror"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/VKID\/SQ","doc:\/\/VKID\/s5ErrorP","doc:\/\/VKID\/SH","doc:\/\/VKID\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/VKID\/documentation\/VKID\/AuthError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Основные ошибки авторизации"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthError"}],"title":"AuthError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:4VKID9AuthErrorO","modules":[{"name":"VKID"}],"navigatorTitle":[{"kind":"identifier","text":"AuthError"}]},"hierarchy":{"paths":[["doc:\/\/VKID\/documentation\/VKID"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/VKID\/documentation\/VKID\/AuthError\/authAlreadyInProgress","doc:\/\/VKID\/documentation\/VKID\/AuthError\/cancelled","doc:\/\/VKID\/documentation\/VKID\/AuthError\/unknown"]},{"title":"Default Implementations","identifiers":["doc:\/\/VKID\/documentation\/VKID\/AuthError\/Equatable-Implementations","doc:\/\/VKID\/documentation\/VKID\/AuthError\/Error-Implementations"],"generated":true}],"references":{"doc://VKID/documentation/VKID/AuthError/unknown":{"role":"symbol","title":"AuthError.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Причина неизвестна"}],"identifier":"doc:\/\/VKID\/documentation\/VKID\/AuthError\/unknown","kind":"symbol","type":"topic","url":"\/documentation\/vkid\/autherror\/unknown"},"doc://VKID/documentation/VKID/AuthError/authAlreadyInProgress":{"role":"symbol","title":"AuthError.authAlreadyInProgress","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authAlreadyInProgress"}],"abstract":[{"type":"text","text":"Процесс авторизации уже начат. Попытка повторного запуска флоу авторизации"}],"identifier":"doc:\/\/VKID\/documentation\/VKID\/AuthError\/authAlreadyInProgress","kind":"symbol","type":"topic","url":"\/documentation\/vkid\/autherror\/authalreadyinprogress"},"doc://VKID/documentation/VKID/AuthError/cancelled":{"role":"symbol","title":"AuthError.cancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"abstract":[{"type":"text","text":"Пользователь прервал\/отменил авторизацию"}],"identifier":"doc:\/\/VKID\/documentation\/VKID\/AuthError\/cancelled","kind":"symbol","type":"topic","url":"\/documentation\/vkid\/autherror\/cancelled"},"doc://VKID/documentation/VKID":{"role":"collection","title":"VKID","abstract":[],"identifier":"doc:\/\/VKID\/documentation\/VKID","kind":"symbol","type":"topic","url":"\/documentation\/vkid"},"doc://VKID/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/VKID\/SQ"},"doc://VKID/documentation/VKID/AuthError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/VKID\/documentation\/VKID\/AuthError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/vkid\/autherror\/equatable-implementations"},"doc://VKID/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/VKID\/s5ErrorP"},"doc://VKID/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/VKID\/SH"},"doc://VKID/documentation/VKID/AuthError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/VKID\/documentation\/VKID\/AuthError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/vkid\/autherror\/error-implementations"},"doc://VKID/documentation/VKID/AuthError":{"role":"symbol","title":"AuthError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthError"}],"abstract":[{"type":"text","text":"Основные ошибки авторизации"}],"identifier":"doc:\/\/VKID\/documentation\/VKID\/AuthError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthError"}],"url":"\/documentation\/vkid\/autherror"},"doc://VKID/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/VKID\/s8SendableP"}}}